name: Run Google Sheets Script

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
  MY_API_KEY: ${{ secrets.MY_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install gspread google-auth

      - name: Run script
        run: python New_Joining.py
